### ISSUE TITLE
developer installation breaks

### ISSUE THREAD

**Issue by nswaldman** [demozoo/demozoo#237]
The current developer installation, as per instructions, breaks and fails to complete.

During the setup in the vagrant image, things trip on the `su - vagrant -c "$PYTHON $PROJECT_DIR/manage.py migrate"` line, see attached log:

````
==> default: Traceback (most recent call last):
==> default:   File "/home/vagrant/demozoo/manage.py", line 9, in <module>
==> default:
==> default: execute_from_command_line(sys.argv)
==> default:   File "/home/vagrant/.virtualenvs/demozoo/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
==> default:
==> default: utility.execute()
==> default:   File "/home/vagrant/.virtualenvs/demozoo/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
==> default:
==> default: self.fetch_command(subcommand).run_from_argv(self.argv)
==> default:   File "/home/vagrant/.virtualenvs/demozoo/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
==> default:
==> default: self.execute(*args, **options.__dict__)
==> default:   File "/home/vagrant/.virtualenvs/demozoo/local/lib/python2.7/site-packages/django/core/management/base.py", line 284, in execute
==> default:
==> default: self.validate()
==> default:   File "/home/vagrant/.virtualenvs/demozoo/local/lib/python2.7/site-packages/django/core/management/base.py", line 310, in validate
==> default:
==> default: num_errors = get_validation_errors(s, app)
==> default:   File "/home/vagrant/.virtualenvs/demozoo/local/lib/python2.7/site-packages/django/core/management/validation.py", line 34, in get_validation_errors
==> default:
==> default: for (app_name, error) in get_app_errors().items():
==> default:   File "/home/vagrant/.virtualenvs/demozoo/local/lib/python2.7/site-packages/django/db/models/loading.py", line 196, in get_app_errors
==> default:
==> default: self._populate()
==> default:   File "/home/vagrant/.virtualenvs/demozoo/local/lib/python2.7/site-packages/django/db/models/loading.py", line 78, in _populate
==> default:
==> default: self.load_app(app_name)
==> default:   File "/home/vagrant/.virtualenvs/demozoo/local/lib/python2.7/site-packages/django/db/models/loading.py", line 99, in load_app
==> default:
==> default: models = import_module('%s.models' % app_name)
==> default:   File "/home/vagrant/.virtualenvs/demozoo/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
==> default:
==> default: __import__(name)
==> default:   File "/home/vagrant/.virtualenvs/demozoo/local/lib/python2.7/site-packages/debug_toolbar/models.py", line 9, in <module>
==> default:
==> default: dt_settings.patch_all()
==> default:   File "/home/vagrant/.virtualenvs/demozoo/local/lib/python2.7/site-packages/debug_toolbar/settings.py", line 214, in patch_all
==> default:
==> default: patch_root_urlconf()
==> default:   File "/home/vagrant/.virtualenvs/demozoo/local/lib/python2.7/site-packages/debug_toolbar/settings.py", line 202, in patch_root_urlconf
==> default:
==> default: reverse('djdt:render_panel')
==> default:   File "/home/vagrant/.virtualenvs/demozoo/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 507, in reverse
==> default:
==> default: app_list = resolver.app_dict[ns]
==> default:   File "/home/vagrant/.virtualenvs/demozoo/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 329, in app_dict
==> default:
==> default: self._populate()
==> default:   File "/home/vagrant/.virtualenvs/demozoo/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 267, in _populate
==> default:
==> default: for pattern in reversed(self.url_patterns):
==> default:   File "/home/vagrant/.virtualenvs/demozoo/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
==> default:
==> default: patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
==> default:   File "/home/vagrant/.virtualenvs/demozoo/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
==> default:     self._urlconf_module = import_module(self.urlconf_name)
==> default:   File "/home/vagrant/.virtualenvs/demozoo/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
==> default:     __import__(name)
==> default:   File "/home/vagrant/demozoo/urls.py", line 5, in <module>
==> default:
==> default: admin.autodiscover()
==> default:   File "/home/vagrant/.virtualenvs/demozoo/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 29, in autodiscover
==> default:     import_module('%s.admin' % app)
==> default:   File "/home/vagrant/.virtualenvs/demozoo/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
==> default:     __import__(name)
==> default:   File "/home/vagrant/.virtualenvs/demozoo/local/lib/python2.7/site-packages/django_extensions/admin/__init__.py", line 10, in <module>
==> default:     from django.apps import apps
==> default: ImportError: No module named apps
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
````

**Comment by jensadne** [comment]
Looks like the problem is that the installed version of django-extensions expects Django 1.7 or higher, the culprit might be me actually since I'm fairly sure I was the one who put django-extensions in requirements.txt without an explicit version number.
